- alias: "Light Theme after Sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: default
        
- alias: "Dark Theme after Sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: dark    

- alias: "Turn Hallway Light on when there is movement"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000200d002
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_158d000200d002
    below: 10
  action:
    - service: light.turn_on
      entity_id: light.hallway

- alias: "Turn off hallway light 1 minutes after last movement"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000200d002
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.hallway

- alias: "Toggle Thomas ceiling light on single press"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef86ec
      click_type: single
  action:
    service: light.toggle
    entity_id: light.thomas  
