- alias: "Light Theme after Sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: default
        
- alias: "Dark Theme after Sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: dark    

- alias: "Turn Hallway Light on when there is movement"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000200d002
    to: 'Detected'
  condition:
    condition: template
    value_template: '{{ sensor.illumination_158d000200d002 < 8 }}'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hallway
      
- alias: "Turn off hallway light 1 minutes after last movement"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000200d002
    to: 'Clear'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: light.hallway
