- alias: "Default Theme after Sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: default
- alias: "dark Theme after Sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: dark    
