# individual lights
- name: "Window 1"
  command_topic: milight/0x2221/rgb_cct/1
  state_topic: milight/state/0x2221/rgb_cct/1
  # Use a YAML anchor for common settings so we can just reference
  # them for other lights.
  <<: &RGB_CCT_MILIGHT_PARAMS
    platform: mqtt
    schema: json
    color_temp: true
    rgb: true
    brightness: true

- name: "Window 2"
  command_topic: milight/0x2221/rgb_cct/2
  state_topic: milight/state/0x2221/rgb_cct/2
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Dining 1"
  command_topic: milight/0x2222/rgb_cct/1
  state_topic: milight/state/0x2222/rgb_cct/1
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Dining 2"
  command_topic: milight/0x2222/rgb_cct/2
  state_topic: milight/state/0x2222/rgb_cct/2
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Hallway"
  command_topic: milight/0x2211/rgb_cct/1
  state_topic: milight/state/0x2211/rgb_cct/1
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Bathroom 1"
  command_topic: milight/0x2B0E/rgb_cct/1
  state_topic: milight/state/0x2B0E/rgb_cct/1
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Bathroom 2"
  command_topic: milight/0x2B0E/rgb_cct/2
  state_topic: milight/state/0x2B0E/rgb_cct/2
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Kitchen 1"
  command_topic: milight/0x2223/rgb_cct/1
  state_topic: milight/state/0x2223/rgb_cct/1
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Kitchen 2"
  command_topic: milight/0x2223/rgb_cct/2
  state_topic: milight/state/0x2223/rgb_cct/2
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Kitchen 3"
  command_topic: milight/0x2223/rgb_cct/3
  state_topic: milight/state/0x2223/rgb_cct/3
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Livingroom Spot 1"
  command_topic: milight/0x2224/rgb_cct/1
  state_topic: milight/state/0x2224/rgb_cct/1
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Livingroom Spot 2"
  command_topic: milight/0x2224/rgb_cct/2
  state_topic: milight/state/0x2224/rgb_cct/2
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Livingroom Spot 3"
  command_topic: milight/0x2224/rgb_cct/3
  state_topic: milight/state/0x2224/rgb_cct/3
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Livingroom Spot 4"
  command_topic: milight/0x2224/rgb_cct/4
  state_topic: milight/state/0x2224/rgb_cct/4
  # Reference YAML anchor defined above.
  <<: *RGB_CCT_MILIGHT_PARAMS

- name: "Thomas"
  command_topic: milight/0x2225/rgbw/1
  state_topic: milight/state/0x2225/rgbw/1
  # Use a YAML anchor for common settings so we can just reference
  # them for other lights.
  <<: &RGBW_MILIGHT_PARAMS
    platform: mqtt
    schema: json
    rgb: true
    brightness: true

# groups
- platform: group
  name: Window Lights
  entities:
    - light.window_1
    - light.window_2

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_1
    - light.bathroom_2

- platform: group
  name: Dining Lights
  entities:
    - light.dining_1
    - light.dining_2

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3

- platform: group
  name: Window Spots
  entities:
    - light.livingroom_spot_1
    - light.livingroom_spot_2
    - light.livingroom_spot_3
    - light.livingroom_spot_4
    
- platform: group
  name: Livingroom Lights
  entities:
    - light.livingroom_spot_1
    - light.livingroom_spot_2
    - light.livingroom_spot_3
    - light.livingroom_spot_4
    - light.window_1
    - light.window_2
