- platform: yr
  name:  Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - windDirection
    - humidity
    - cloudiness
    - dewpointTemperature

- platform: postnl
  username: !secret postnl_username
  password: !secret postnl_password

- platform: pi_hole
  host: 192.168.41.2
  verify_ssl: false
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - unique_clients
