resources:
  - url: /local/slider-entity-row.js?v=46be70e
    type: js
  - url: /local/mini-media-player-bundle.js?v=1.1.3
    type: module
  - url: /local/mini-graph-card/dist/mini-graph-card-bundle.js?v=0.4.2
    type: module
title: Home
views:
  - badges: []
    cards:
      - cards:
          - entity: light.window_lights
            hold_action:
              action: more-info
            icon: 'mdi:sofa'
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            theme: Backend-selected
            type: entity-button
          - entity: light.window_spots
            hold_action:
              action: more-info
            icon: 'mdi:track-light'
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            theme: Backend-selected
            type: entity-button
          - entity: light.dining_lights
            hold_action:
              action: more-info
            icon: 'mdi:silverware-fork-knife'
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            theme: Backend-selected
            type: entity-button
          - entity: light.kitchen_lights
            hold_action:
              action: more-info
            icon: 'mdi:stove'
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            theme: Backend-selected
            type: entity-button
        type: horizontal-stack
      - cards:
          - entity: sensor.temperature_158d000247fe4d
            type: gauge
            min: 10
            max: 30
            severity:
              red: 24
              green: 19.5
              blue: 10
          - entity: sensor.humidity_158d000247fe4d
            severity:
              red: 70
              green: 40
              yellow: 10
            type: gauge
          - entity: sensor.illumination_158d000200e334
            type: gauge
        type: horizontal-stack
      - entities:
          - type: custom:slider-entity-row
            entity: light.window_lights
            icon: mdi:lamp
          - entity: light.window_spots
            type: custom:slider-entity-row
            icon: mdi:wall-sconce-flat
          - entity: light.dining_lights
            type: custom:slider-entity-row
            icon: mdi:ceiling-light
          - entity: light.kitchen_lights
            type: custom:slider-entity-row
            icon: mdi:track-light
          - entity: light.quinled01_led1
            type: custom:slider-entity-row
            icon: mdi:mdi-car-parking-lights
          - entity: light.quinled01_led2
            type: custom:slider-entity-row
            icon: mdi:mdi-car-parking-lights
          - switch.74603836cc50e3430c30
          - binary_sensor.motion_sensor_158d000200e334
          - sensor.temperature_158d000247fe4d
          - sensor.humidity_158d000247fe4d
          - sensor.pressure_158d000247fe4d
          - sensor.illumination_158d000200e334
          - binary_sensor.door_window_sensor_158d000232da17
        show_header_toggle: true
        title: Living Room
        type: entities
      - entities:
          - light.hallway
          - binary_sensor.motion_sensor_158d000200d002
          - sensor.illumination_158d000200d002
          - binary_sensor.door_window_sensor_158d0002045c91
          - binary_sensor.door_window_sensor_158d00020b540e
          - sensor.illumination_7811dcb8f32b
        show_header_toggle: false
        title: Hallway
        type: entities
      - type: weather-forecast
        entity: weather.dark_sky
      - type: horizontal-stack
        cards:
          - entity: sensor.unifi_gateway_3_kbyte_sec_received
            type: gauge
            max: 25000
            min: 0
            name: Ingress
            unit: kB/s
            severity:
              green: 0
              yellow: 17500
              red: 22500
          - entity: sensor.unifi_gateway_3_kbyte_sec_sent
            type: gauge
            max: 2500
            min: 0
            name: Egress
            unit: kB/s
            severity:
              green: 0
              yellow: 1750
              red: 2250
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            type: gauge
            name: PiHole Block %
            max: 100
            
      - entities:
          - sensor.temperature_158d00022c7d5c
          - sensor.humidity_158d00022c7d5c
          - sensor.temperature_158d0001f52f1f
          - sensor.humidity_158d0001f52f1f
          - sensor.temperature_158d000247cdb5
          - sensor.humidity_158d000247cdb5
          - sensor.temperature_158d0001fa75cc
          - sensor.humidity_158d0001fa75cc
          - sensor.illumination_7811dcb7e280
          - binary_sensor.switch_158d00023db266
          - binary_sensor.switch_158d0001ef86ec
        show_header_toggle: false
        title: Bedroom
        type: entities
      - entities:
          - light.bathroom_lights
          - light.bathroom_1
          - light.bathroom_2
          - sensor.temperature_158d00022cdd46
          - sensor.humidity_158d00022cdd46
          - binary_sensor.motion_sensor_158d000200cfee
          - sensor.illumination_158d000200cfee
        show_header_toggle: false
        title: Bathroom
        type: entities
      - entities:
          - entity: sun.sun
          - entity: sensor.weather_symbol
          - entity: sensor.weather_temperature
          - entity: sensor.weather_humidity
            icon: mdi:water-percent
          - entity: sensor.weather_wind_direction
            icon: mdi:compass-outline
          - entity: sensor.weather_wind_speed
            icon: mdi:weather-windy
          - entity: sensor.weather_precipitation
            icon: mdi:weather-rainy
          - entity: sensor.weather_cloudiness
            icon: mdi:cloud-question
          - entity: sensor.weather_dewpoint_temperature
        show_header_toggle: false
        title: Weather
        type: entities
      - entities:
          - switch.shed_socket_1
          - switch.shed_socket_2
        show_header_toggle: false
        title: Switch
        type: entities
    icon: 'mdi:home-automation'
    path: default_view
    theme: default
    title: Livingroom
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: sensor.temperature_158d00022c7d5c
                graph: line
                type: sensor
              - entity: sensor.humidity_158d00022c7d5c
                graph: line
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.temperature_158d0001f52f1f
                graph: line
                type: sensor
              - entity: sensor.humidity_158d0001f52f1f
                graph: line
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.temperature_158d00022cdd46
                graph: line
                type: sensor
              - entity: sensor.humidity_158d00022cdd46
                graph: line
                type: sensor
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - cards:
              - entity: sensor.temperature_158d000247cdb5
                graph: line
                type: sensor
              - entity: sensor.humidity_158d000247cdb5
                graph: line
                type: sensor
            type: horizontal-stack
          - cards:
              - entity: sensor.temperature_158d0001fa75cc
                graph: line
                type: sensor
              - entity: sensor.humidity_158d0001fa75cc
                graph: line
                type: sensor
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:bed-empty'
    title: Bedrooms
  - badges: []
    cards:
      - entity: light.dining_lights
        name: Dining
        type: light
      - entities:
          - light.window_lights
          - light.window_1
          - light.window_2
        show_header_toggle: false
        title: Window Sill
        type: entities
      - entities:
          - light.window_spots
          - light.livingroom_spot_1
          - light.livingroom_spot_2
          - light.livingroom_spot_3
          - light.livingroom_spot_4
        show_header_toggle: false
        title: Livingroom Spots
        type: entities
      - entities:
          - entity: light.kitchen_lights
          - entity: light.kitchen_1
            icon: mdi:track-light
          - entity: light.kitchen_2
            icon: mdi:track-light
          - entity: light.kitchen_3
            icon: mdi:track-light
          - entity: binary_sensor.kitchen_motion
        show_header_toggle: false
        title: Kitchen
        type: entities
      - entities:
          - entity: light.thomas
            type: custom:slider-entity-row
          - entity: light.fenna_spots
            type: custom:slider-entity-row
          - entity: light.fenna_spot_1
            icon: mdi:wall-sconce-flat
          - entity: light.fenna_spot_2
            icon: mdi:wall-sconce-flat
          - entity: light.fenna_spot_3
            icon: mdi:wall-sconce-flat
          - entity: light.fenna_spot_4
            icon: mdi:wall-sconce-flat
        title: Bedroom
        type: entities
      - entities:
          - light.gateway_light_7811dcb8f32b
          - light.gateway_light_7811dcb7e280
        title: Xiaomi Hubs
        type: entities
      - entities:
          - light.dining_lights
          - light.dining_1
          - light.dining_2
          - switch.circadian_lighting_circadian_lights
        show_header_toggle: false
        title: Dining
        type: entities
    icon: 'mdi:lightbulb-on'
    title: Lights
  - badges: []
    cards:
      - type: custom:mini-media-player
        entity: media_player.tv
        artwork: full-cover
        icon: 'mdi:cast'
        hide:
          volume: false
          source: true
          power_state: false
      #- entity: media_player.tv
      #  type: media-control
      - type: custom:mini-media-player
        entity: media_player.bedroom_speaker
        artwork: cover
        icon: mdi:google-home
        hide:
          volume: false
          source: true
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.speakers
        artwork: cover
        icon:  mdi:speaker-multiple
        hide:
          volume: false
          source: true
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.stereo_speaker
        artwork: cover
        icon:  mdi:speaker-multiple
        hide:
          volume: false
          source: true
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.kitchen_speaker
        artwork: cover
        icon: mdi:speaker-wireless
        hide:
          volume: false
          source: true
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.google_home
        artwork: cover
        icon: mdi:google-home
        hide:
          volume: false
          source: true
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.samsung_tv_remote
        artwork: cover
        icon: 'mdi:youtube-tv'
        hide:
          volume: true
          source: true
          power_state: false
    icon: 'mdi:google'
    title: Media
