esphome:
  name: motion01
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

# Enable Web server
web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: esphome_motion01_wifi_signal
    update_interval: 30s
  - platform: uptime
    name: esphome_motion01_uptime

switch:
  - platform: restart
    name: esphome_motion01_restart
    
binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "Kitchen Motion"

text_sensor:
  - platform: version
    name: esphome_motion01_version
